# -*- coding: utf-8 -*-
"""Heston_simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZoN6lPNfQkDbIT1Pz8yr1zuQEIVFvmX_
"""

import numpy as np

class HestonModelSimulator:
    def __init__(self, params: HestonParams, config: MonteCarloConfig):
        # Validate configurations before starting simulation
        params.validate()
        config.validate()

        self.params = params
        self.config = config

    def simulate(self):
    p = self.params
    c = self.config
    dt = c.maturity / c.n_steps
    rng = np.random.default_rng(c.seed)

    S = np.zeros((c.n_paths, c.n_steps + 1))
    v = np.zeros((c.n_paths, c.n_steps + 1))

    S[:, 0] = p.s0
    v[:, 0] = p.v0

    for t in range(1, c.n_steps + 1):
        # Use utils helper
        z_s, z_v = make_correlated_normals(c.n_paths, p.rho, rng)

        v_prev = v[:, t-1]
        v_plus = np.maximum(v_prev, 0)

        # Variance update
        v[:, t] = v_prev + p.kappa * (p.theta - v_plus) * dt + \
                  p.sigma * np.sqrt(v_plus * dt) * z_v

        # Asset update (Simple Returns)
        S[:, t] = S[:, t-1] * (1 + (p.r - p.q) * dt + np.sqrt(v_plus * dt) * z_s)
        S[:, t] = np.maximum(S[:, t], 0)

    return S, v